/**
 * One-shot script: lifts the captured /tmp/yt-demo-data/all.json (DB
 * snapshot of cached video summaries + transcript segments) into typed
 * per-video TypeScript modules under app/components/hero-demo-data/.
 *
 * Run on demand to refresh demo data when the cached summaries drift:
 *   pnpm tsx scripts/build-hero-demo-data.ts
 *
 * Re-running overwrites the per-video files. The index file
 * (`app/components/hero-demo-data/index.ts`) is NOT regenerated — that
 * one is hand-curated.
 *
 * Source-snapshot regeneration: re-run the SQL on Supabase and dump it
 * to /tmp/yt-demo-data/all.json. See
 * docs/superpowers/specs/2026-04-30-hero-demo-widget-design.md
 * "Pre-captured snapshot" for the exact query.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

const VIDEO_IDS = [
  "Hrbq66XqtCo",
  "nm1TxQj9IsQ",
  "Mde2q7GFCrw",
  "csA9YhzYvmk",
  "BWJ4vnXIvts",
] as const;

// Truncate transcripts at this length per sample to keep per-file payload
// small. The full transcript stays accessible behind a "View full
// transcript on /summary →" link.
const SEGMENT_LIMIT = 30;

interface CapturedRecord {
  youtubeId: string;
  youtubeUrl: string;
  title: string;
  channel: string;
  durationSec: number;
  summary: string;
  segments: Array<{ text: string; start: number; duration: number }>;
  model: string;
}

async function main(): Promise<void> {
  const raw = await readFile("/tmp/yt-demo-data/all.json", "utf8");
  const data = JSON.parse(raw) as Record<string, CapturedRecord>;
  const outDir = "app/components/hero-demo-data";
  await mkdir(outDir, { recursive: true });

  for (const id of VIDEO_IDS) {
    const r = data[id];
    if (!r) {
      throw new Error(`Missing captured data for ${id}`);
    }

    const truncated = r.segments.slice(0, SEGMENT_LIMIT);

    const file = `// AUTO-GENERATED by scripts/build-hero-demo-data.ts. Do not edit by hand.
// Re-run \`pnpm tsx scripts/build-hero-demo-data.ts\` to refresh.

import type { SampleData } from "./index";

const data: SampleData = {
  id: ${JSON.stringify(id)},
  summary: ${JSON.stringify(r.summary)},
  segments: ${JSON.stringify(truncated)},
  model: ${JSON.stringify(r.model)},
};

export default data;
`;
    await writeFile(join(outDir, `${id}.ts`), file, "utf8");
    console.log(
      `wrote ${outDir}/${id}.ts (${file.length.toLocaleString()} chars)`
    );
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
