/**
 * Materialize per-id directories for the hero demo widget.
 *
 *   /tmp/yt-demo-data/all.json
 *     → app/components/hero-demo-data/<id>/base.ts          (transcript + meta)
 *     → app/components/hero-demo-data/<id>/<lang>.ts        (summary per language; 17 files)
 *
 * Input shape (produced by the seed/dump pipeline — see
 * scripts/seed-hero-demo-translations.ts and the SQL dump in the
 * 2026-04-30-hero-demo-improvements plan):
 *
 *   {
 *     "<id>": {
 *       "youtubeId": "<id>",
 *       "title": "...",
 *       "channel": "...",
 *       "durationSec": 1234 | null,
 *       "nativeLanguage": "en" | null,
 *       "segments": [{ text, start, duration }, ...],
 *       "summaries": { "en": { summary, model }, "es": ..., ... }
 *     }
 *   }
 *
 * Run on demand:
 *   pnpm tsx scripts/build-hero-demo-data.ts
 *
 * Re-running overwrites the per-video files. The index file
 * (app/components/hero-demo-data/index.ts) is hand-curated; this
 * script does not regenerate it.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

import { HERO_DEMO_VIDEO_IDS } from "../lib/constants/hero-demo-ids";
import { SUPPORTED_OUTPUT_LANGUAGES } from "../lib/constants/languages";
import { SuggestedFollowupsSchema } from "../lib/services/suggested-followups-schema";
import type { TranscriptSegment } from "../app/components/hero-demo-data";

interface CapturedSummary {
  readonly summary: string;
  readonly model: string;
  readonly suggestions: readonly [string, string, string];
}

interface CapturedRecord {
  readonly youtubeId: string;
  readonly title: string;
  readonly channel: string;
  readonly durationSec: number | null;
  readonly nativeLanguage: string | null;
  readonly segments: TranscriptSegment[];
  readonly summaries: Record<string, CapturedSummary>;
}

async function main(): Promise<void> {
  const raw = await readFile("/tmp/yt-demo-data/all.json", "utf8");
  const data = JSON.parse(raw) as Record<string, CapturedRecord>;
  const outRoot = "app/components/hero-demo-data";
  const allLangs = SUPPORTED_OUTPUT_LANGUAGES.map((l) => l.code);

  for (const id of HERO_DEMO_VIDEO_IDS) {
    const r = data[id];
    if (!r) {
      throw new Error(`Missing captured data for ${id}`);
    }
    const dir = join(outRoot, id);
    await mkdir(dir, { recursive: true });

    const baseSrc = `// AUTO-GENERATED by scripts/build-hero-demo-data.ts. Do not edit by hand.
// Re-run \`pnpm tsx scripts/build-hero-demo-data.ts\` to refresh.

import type { HeroSampleBase } from "../index";

const data: HeroSampleBase = {
  id: ${JSON.stringify(id)},
  segments: ${JSON.stringify(r.segments)},
  nativeLanguage: ${JSON.stringify(r.nativeLanguage)},
};

export default data;
`;
    await writeFile(join(dir, "base.ts"), baseSrc, "utf8");

    for (const lang of allLangs) {
      const s = r.summaries[lang];
      if (!s) {
        throw new Error(`MISSING (${id}, ${lang}) — re-run the seed script.`);
      }
      // Same loud-failure mode as the missing-summary guard: the build
      // halts so the dev re-runs `seed-hero-demo-suggestions.ts` rather
      // than silently emitting an `undefined` or wrong-shape field.
      // Reuses the runtime SuggestedFollowupsSchema so the cardinality
      // and per-string min/max length invariants stay in one place.
      const guard = SuggestedFollowupsSchema.safeParse(s.suggestions);
      if (!guard.success) {
        throw new Error(
          `INVALID SUGGESTIONS (${id}, ${lang}) — run scripts/seed-hero-demo-suggestions.ts. ` +
            `Issue: ${guard.error.issues[0]?.message ?? "unknown"}`,
        );
      }
      const langSrc = `// AUTO-GENERATED by scripts/build-hero-demo-data.ts. Do not edit by hand.

import type { HeroSampleSummary } from "../index";

const data: HeroSampleSummary = {
  id: ${JSON.stringify(id)},
  language: ${JSON.stringify(lang)},
  summary: ${JSON.stringify(s.summary)},
  model: ${JSON.stringify(s.model)},
  suggestions: ${JSON.stringify(s.suggestions)} as const,
};

export default data;
`;
      await writeFile(join(dir, `${lang}.ts`), langSrc, "utf8");
    }

    console.log(
      `wrote ${dir}/{base, ${allLangs.length} langs}.ts`,
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
